## Tutorial 5
### Pandas: Resampling and DataFrame

In [4]:
# Primero es necesario importar las librerias para traer los datos

import pandas as pd
!pip install quandl
import quandl
quandl.ApiConfig.api_key = 'DDoRXaXzshJm_UGBYDVL'

Requirement already satisfied: quandl in /usr/local/lib/python3.7/dist-packages (3.6.1)
Requirement already satisfied: numpy>=1.8 in /usr/local/lib/python3.7/dist-packages (from quandl) (1.19.5)
Requirement already satisfied: requests>=2.7.0 in /usr/local/lib/python3.7/dist-packages (from quandl) (2.23.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from quandl) (2.8.1)
Requirement already satisfied: pandas>=0.14 in /usr/local/lib/python3.7/dist-packages (from quandl) (1.1.5)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.7/dist-packages (from quandl) (8.7.0)
Requirement already satisfied: inflection>=0.3.1 in /usr/local/lib/python3.7/dist-packages (from quandl) (0.5.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from quandl) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.7.0->quandl) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.7.0->quandl) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.7.0->quandl) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.7.0->quandl) (1.24.3)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.14->quandl) (2018.9)

In [6]:
# Primero es necesario crear una cuenta en la pagina y desde ahí, obtener la key


aapl_table = quandl.get('WIKI/AAPL')
aapl = aapl_table['Adj. Close']['2017']
print (aapl)

Date
2017-01-03    114.715378
2017-01-04    114.586983
2017-01-05    115.169696
2017-01-06    116.453639
2017-01-09    117.520300
                 ...
2017-12-22    175.010000
2017-12-26    170.570000
2017-12-27    170.600000
2017-12-28    171.080000
2017-12-29    169.230000
Name: Adj. Close, Length: 249, dtype: float64

In [8]:
# Se esta imprimiendo desde una fecha especifica

print (aapl['2017-3'])

Date
2017-03-01    138.657681
2017-03-02    137.834404
2017-03-03    138.647762
2017-03-06    138.211326
2017-03-07    138.389868
2017-03-08    137.874080
2017-03-09    137.556672
2017-03-10    138.012946
2017-03-13    138.072460
2017-03-14    137.864161
2017-03-15    139.322254
2017-03-16    139.550391
2017-03-17    138.856061
2017-03-20    140.314154
2017-03-21    138.707276
2017-03-22    140.274478
2017-03-23    139.778528
2017-03-24    139.500796
2017-03-27    139.738852
2017-03-28    142.635200
2017-03-29    142.952608
2017-03-30    142.764147
2017-03-31    142.496334
Name: Adj. Close, dtype: float64

In [9]:
# Tambien se puede obtener la información de diferentes periodos
print(aapl['2017-2':'2017-4'])

Date
2017-02-01    127.159749
2017-02-02    126.942467
2017-02-03    127.485673
2017-02-06    128.680728
2017-02-07    129.905412
                 ...
2017-04-24    142.476496
2017-04-25    143.369205
2017-04-26    142.487208
2017-04-27    142.625281
2017-04-28    142.486415
Name: Adj. Close, Length: 61, dtype: float64

In [10]:
# Imprimir los primeros 5 y los ultimos 10 
print (aapl.head())
print (aapl.tail(10))

Date
2017-01-03    114.715378
2017-01-04    114.586983
2017-01-05    115.169696
2017-01-06    116.453639
2017-01-09    117.520300
Name: Adj. Close, dtype: float64
Date
2017-12-15    173.87
2017-12-18    176.42
2017-12-19    174.54
2017-12-20    174.35
2017-12-21    175.01
2017-12-22    175.01
2017-12-26    170.57
2017-12-27    170.60
2017-12-28    171.08
2017-12-29    169.23
Name: Adj. Close, dtype: float64

In [11]:
# resample agrupa la infomación en pequeñas series, dependiendo de lo que se solicite
# Y ademas se puede pasara como parametro la media de las nuevas series geradas
by_month = aapl.resample('M').mean()
print(by_month)

Date
2017-01-31    118.093136
2017-02-28    132.456268
2017-03-31    139.478802
2017-04-30    141.728436
2017-05-31    151.386305
2017-06-30    147.233064
2017-07-31    147.706190
2017-08-31    158.856375
2017-09-30    157.606500
2017-10-31    157.811627
2017-11-30    172.214500
2017-12-31    171.893100
Freq: M, Name: Adj. Close, dtype: float64

In [12]:
by_week = aapl.resample('W').mean()
print (by_week.head())

Date
2017-01-08    115.231424
2017-01-15    117.755360
2017-01-22    118.461035
2017-01-29    119.667448
2017-02-05    124.313346
Freq: W-SUN, Name: Adj. Close, dtype: float64

In [15]:
three_day = aapl.resample('3D').mean()
two_week  = aapl.resample('2W').mean()
two_month = aapl.resample('2M').mean()
print(three_day)
print(two_week)
print(two_month)

Date
2017-01-03    114.824019
2017-01-06    116.453639
2017-01-09    117.810010
2017-01-12    117.673385
2017-01-15    118.517825
                 ...
2017-12-17    175.480000
2017-12-20    174.790000
2017-12-23           NaN
2017-12-26    170.750000
2017-12-29    169.230000
Freq: 3D, Name: Adj. Close, Length: 121, dtype: float64
Date
2017-01-08    115.231424
2017-01-22    118.068993
2017-02-05    121.990397
2017-02-19    132.081078
2017-03-05    136.601142
2017-03-19    138.371022
2017-04-02    140.916237
2017-04-16    141.857109
2017-04-30    141.612630
2017-05-14    149.598217
2017-05-28    152.932484
2017-06-11    153.021346
2017-06-25    144.695904
2017-07-09    143.594041
2017-07-23    147.841142
2017-08-06    152.018194
2017-08-20    158.929140
2017-09-03    161.188000
2017-09-17    160.445556
2017-10-01    154.407000
2017-10-15    155.371080
2017-10-29    158.238500
2017-11-12    171.430000
2017-11-26    172.076667
2017-12-10    170.681200
2017-12-24    173.806000
2018-01-07    170.370000
Freq: 2W-SUN, Name: Adj. Close, dtype: float64
Date
2017-01-31    118.093136
2017-03-31    136.301941
2017-05-31    146.910707
2017-07-31    147.458362
2017-09-30    158.261196
2017-11-30    164.670138
2018-01-31    171.893100
Freq: 2M, Name: Adj. Close, dtype: float64

In [16]:
std = aapl.resample('W').std()    # standard deviation
max = aapl.resample('W').max()    # maximum value
min = aapl.resample('W').min()    # minimum value

# Tambien se pueden usar otro tipo de funciones
print(std)
print(max)
print(min)

Date
2017-01-08    0.852296
2017-01-15    0.303965
2017-01-22    0.107097
2017-01-29    1.027976
2017-02-05    3.953127
2017-02-12    1.054342
2017-02-19    0.969247
2017-02-26    0.248701
2017-03-05    1.425250
2017-03-12    0.319693
2017-03-19    0.745266
2017-03-26    0.659058
2017-04-02    1.340247
2017-04-09    0.539305
2017-04-16    0.890443
2017-04-23    0.732013
2017-04-30    0.385246
2017-05-07    0.983818
2017-05-14    1.480644
2017-05-21    2.250808
2017-05-28    0.253079
2017-06-04    1.178505
2017-06-11    2.598342
2017-06-18    1.593357
2017-06-25    0.555420
2017-07-02    1.104805
2017-07-09    0.665854
2017-07-16    1.694205
2017-07-23    0.523784
2017-07-30    1.611054
2017-08-06    3.836757
2017-08-13    2.272546
2017-08-20    1.821903
2017-08-27    1.155790
2017-09-03    1.055026
2017-09-10    1.599521
2017-09-17    1.226206
2017-09-24    3.081331
2017-10-01    1.487222
2017-10-08    0.867246
2017-10-15    0.497624
2017-10-22    2.190114
2017-10-29    2.852625
2017-11-05    2.349930
2017-11-12    0.693752
2017-11-19    1.821639
2017-11-26    2.351374
2017-12-03    1.785083
2017-12-10    0.299377
2017-12-17    0.816474
2017-12-24    0.810697
2017-12-31    0.795110
Freq: W-SUN, Name: Adj. Close, dtype: float64
Date
2017-01-08    116.453639
2017-01-15    118.270913
2017-01-22    118.517825
2017-01-29    120.443739
2017-02-05    127.485673
2017-02-12    131.347379
2017-02-19    134.620649
2017-02-26    135.999390
2017-03-05    138.657681
2017-03-12    138.389868
2017-03-19    139.550391
2017-03-26    140.314154
2017-04-02    142.952608
2017-04-09    143.597342
2017-04-16    142.010303
2017-04-23    141.286216
2017-04-30    143.369205
2017-05-07    147.753403
2017-05-14    155.469192
2017-05-21    155.070808
2017-05-28    153.367718
2017-06-04    154.821818
2017-06-11    154.742142
2017-06-18    145.997622
2017-06-25    145.758592
2017-07-02    145.240693
2017-07-09    143.597361
2017-07-16    148.437722
2017-07-23    150.409720
2017-07-30    152.839860
2017-08-06    156.504989
2017-08-13    160.409148
2017-08-20    161.600000
2017-08-27    159.980000
2017-09-03    164.050000
2017-09-10    162.080000
2017-09-17    161.500000
2017-09-24    158.730000
2017-10-01    154.230000
2017-10-08    155.390000
2017-10-15    156.990000
2017-10-22    160.470000
2017-10-29    163.050000
2017-11-05    172.500000
2017-11-12    175.880000
2017-11-19    173.970000
2017-11-26    174.970000
2017-12-03    174.090000
2017-12-10    169.800000
2017-12-17    173.870000
2017-12-24    176.420000
2017-12-31    171.080000
Freq: W-SUN, Name: Adj. Close, dtype: float64
Date
2017-01-08    114.586983
2017-01-15    117.520300
2017-01-22    118.300542
2017-01-29    118.488195
2017-02-05    119.851150
2017-02-12    128.680728
2017-02-19    132.210332
2017-02-26    135.424088
2017-03-05    135.820848
2017-03-12    137.556672
2017-03-19    137.864161
2017-03-26    138.707276
2017-04-02    139.738852
2017-04-09    142.178926
2017-04-16    139.907475
2017-04-23    139.540472
2017-04-30    142.476496
2017-05-07    145.343086
2017-05-14    151.760678
2017-05-21    149.642832
2017-05-28    152.720345
2017-06-04    152.142689
2017-06-11    148.377964
2017-06-18    141.695080
2017-06-25    144.424007
2017-07-02    143.099382
2017-07-09    142.153221
2017-07-16    144.473805
2017-07-23    148.955620
2017-07-30    148.895863
2017-08-06    148.248489
2017-08-13    155.270000
2017-08-20    157.500000
2017-08-27    157.210000
2017-09-03    161.470000
2017-09-10    158.630000
2017-09-17    158.280000
2017-09-24    151.890000
2017-10-01    150.550000
2017-10-08    153.450800
2017-10-15    155.840000
2017-10-22    155.980000
2017-10-29    156.170000
2017-11-05    166.720000
2017-11-12    174.250000
2017-11-19    169.080000
2017-11-26    169.980000
2017-12-03    169.480000
2017-12-10    169.010000
2017-12-17    171.700000
2017-12-24    174.350000
2017-12-31    169.230000
Freq: W-SUN, Name: Adj. Close, dtype: float64

In [17]:
#Se puede usar una función lamda para indicar el ultimo elemento de la serie

last_day = aapl.resample('M').agg(lambda x: x[-1])
print (last_day)

Date
2017-01-31    119.851150
2017-02-28    135.880362
2017-03-31    142.496334
2017-04-30    142.486415
2017-05-31    152.142689
2017-06-30    143.438008
2017-07-31    148.248489
2017-08-31    164.000000
2017-09-30    154.120000
2017-10-31    169.040000
2017-11-30    171.850000
2017-12-31    169.230000
Freq: M, Name: Adj. Close, dtype: float64

In [18]:
monthly_return = aapl.resample('M').agg(lambda x: x[-1]/x[1] - 1)
print (monthly_return)

Date
2017-01-31    0.045940
2017-02-28    0.070409
2017-03-31    0.033823
2017-04-30   -0.007736
2017-05-31    0.039829
2017-06-30   -0.073528
2017-07-31    0.033035
2017-08-31    0.047890
2017-09-30   -0.049112
2017-10-31    0.094252
2017-11-30    0.022247
2017-12-31   -0.003357
Freq: M, Name: Adj. Close, dtype: float64

In [19]:
print (monthly_return.mean())
print (monthly_return.std())
print (monthly_return.max())

0.02114094011940022
0.04775652864223314
0.09425168306576914

In [20]:
# Diff sirve para calcular la diferencia entre elementos consecutivos
# y pct_change es para el calculo del porcentaje de cambio

print(last_day.diff())
print (last_day.pct_change())

Date
2017-01-31          NaN
2017-02-28    16.029211
2017-03-31     6.615972
2017-04-30    -0.009919
2017-05-31     9.656274
2017-06-30    -8.704681
2017-07-31     4.810482
2017-08-31    15.751511
2017-09-30    -9.880000
2017-10-31    14.920000
2017-11-30     2.810000
2017-12-31    -2.620000
Freq: M, Name: Adj. Close, dtype: float64
Date
2017-01-31         NaN
2017-02-28    0.133743
2017-03-31    0.048690
2017-04-30   -0.000070
2017-05-31    0.067770
2017-06-30   -0.057214
2017-07-31    0.033537
2017-08-31    0.106251
2017-09-30   -0.060244
2017-10-31    0.096808
2017-11-30    0.016623
2017-12-31   -0.015246
Freq: M, Name: Adj. Close, dtype: float64

In [21]:
# Se pueden llenar Not a Number con algún valor que se desee
daily_return = last_day.pct_change()
print (daily_return.fillna(0))

Date
2017-01-31    0.000000
2017-02-28    0.133743
2017-03-31    0.048690
2017-04-30   -0.000070
2017-05-31    0.067770
2017-06-30   -0.057214
2017-07-31    0.033537
2017-08-31    0.106251
2017-09-30   -0.060244
2017-10-31    0.096808
2017-11-30    0.016623
2017-12-31   -0.015246
Freq: M, Name: Adj. Close, dtype: float64

In [22]:
# Tambien se pueden llenar con un metodo preestablecido

daily_return = last_day.pct_change()
print (daily_return.fillna(method = 'bfill'))

Date
2017-01-31    0.133743
2017-02-28    0.133743
2017-03-31    0.048690
2017-04-30   -0.000070
2017-05-31    0.067770
2017-06-30   -0.057214
2017-07-31    0.033537
2017-08-31    0.106251
2017-09-30   -0.060244
2017-10-31    0.096808
2017-11-30    0.016623
2017-12-31   -0.015246
Freq: M, Name: Adj. Close, dtype: float64

In [23]:
# Con drop na solamente se estan removiendo de la serie 

daily_return = last_day.pct_change().dropna()
print (daily_return)

Date
2017-02-28    0.133743
2017-03-31    0.048690
2017-04-30   -0.000070
2017-05-31    0.067770
2017-06-30   -0.057214
2017-07-31    0.033537
2017-08-31    0.106251
2017-09-30   -0.060244
2017-10-31    0.096808
2017-11-30    0.016623
2017-12-31   -0.015246
Freq: M, Name: Adj. Close, dtype: float64

## Utlizando DataFrames

In [24]:
# Se puede crear un data frame desde pasandole un diccionario

dict = {'AAPL': [143.5,  144.09, 142.73, 144.18, 143.77],
        'GOOG': [898.7,  911.71, 906.69, 918.59, 926.99],
        'IBM':  [155.58, 153.67, 152.36, 152.94, 153.49]}
dates = pd.date_range('2017-07-03', periods = 5, freq = 'D')
df = pd.DataFrame(dict, index = dates)
print(df)

              AAPL    GOOG     IBM
2017-07-03  143.50  898.70  155.58
2017-07-04  144.09  911.71  153.67
2017-07-05  142.73  906.69  152.36
2017-07-06  144.18  918.59  152.94
2017-07-07  143.77  926.99  153.49

In [26]:
# De esta manera se pueden manipular los dataframes 

df = aapl_table
print (df.Close.tail(5))
print (df['Adj. Volume'].tail(5))

Date
2018-03-21    171.270
2018-03-22    168.845
2018-03-23    164.940
2018-03-26    172.770
2018-03-27    168.340
Name: Close, dtype: float64
Date
2018-03-21    35247358.0
2018-03-22    41051076.0
2018-03-23    40248954.0
2018-03-26    36272617.0
2018-03-27    38962839.0
Name: Adj. Volume, dtype: float64

In [27]:
aapl_2016 = df['2016']
aapl_month = aapl_2016.resample('M').agg(lambda x: x[-1])
print (aapl_month)

              Open      High     Low  ...    Adj. Low  Adj. Close  Adj. Volume
Date                                  ...
2016-01-31   94.79   97.3400   94.35  ...   91.156128   94.044912   64416504.0
2016-02-29   96.86   98.2300   96.65  ...   93.880927   93.919781   35216277.0
2016-03-31  109.72  109.9000  108.88  ...  105.760531  105.867380   25888449.0
2016-04-30   93.99   94.7200   92.51  ...   89.859540   91.054300   68531478.0
2016-05-31   99.60  100.4000   98.82  ...   96.575559   97.591939   42307212.0
2016-06-30   94.44   95.7700   94.30  ...   92.158220   93.428693   35836356.0
2016-07-31  104.19  104.5500  103.68  ...  101.325177  101.843140   27733688.0
2016-08-31  105.66  106.5699  105.64  ...  103.796505  104.248477   29662406.0
2016-09-30  112.46  113.3700  111.80  ...  109.849008  111.077195   36379106.0
2016-10-31  113.65  114.2300  113.20  ...  111.224577  111.558644   26419398.0
2016-11-30  111.56  112.2000  110.27  ...  108.908004  109.154917   36162258.0
2016-12-31  116.65  117.2000  115.43  ...  114.004271  114.389454   30586265.0

[12 rows x 12 columns]

In [29]:
# Igualmente se pueden acceder a los atributos por los nombres

aapl_bar = aapl_month[['Open', 'High', 'Low', 'Close']]
print(aapl_bar)

              Open      High     Low   Close
Date
2016-01-31   94.79   97.3400   94.35   97.34
2016-02-29   96.86   98.2300   96.65   96.69
2016-03-31  109.72  109.9000  108.88  108.99
2016-04-30   93.99   94.7200   92.51   93.74
2016-05-31   99.60  100.4000   98.82   99.86
2016-06-30   94.44   95.7700   94.30   95.60
2016-07-31  104.19  104.5500  103.68  104.21
2016-08-31  105.66  106.5699  105.64  106.10
2016-09-30  112.46  113.3700  111.80  113.05
2016-10-31  113.65  114.2300  113.20  113.54
2016-11-30  111.56  112.2000  110.27  110.52
2016-12-31  116.65  117.2000  115.43  115.82

In [31]:
# Se pueden especificar columnas con loc

print (aapl_month.loc['2016-03':'2016-06', ['Open', 'High', 'Low', 'Close']])

              Open    High     Low   Close
Date
2016-03-31  109.72  109.90  108.88  108.99
2016-04-30   93.99   94.72   92.51   93.74
2016-05-31   99.60  100.40   98.82   99.86
2016-06-30   94.44   95.77   94.30   95.60

In [32]:
# Se puede crear un subset apartir de un dataframe existente 

aapl_bar['rate_return'] = aapl_bar.Close.pct_change()
print(aapl_bar)

              Open      High     Low   Close  rate_return
Date
2016-01-31   94.79   97.3400   94.35   97.34          NaN
2016-02-29   96.86   98.2300   96.65   96.69    -0.006678
2016-03-31  109.72  109.9000  108.88  108.99     0.127211
2016-04-30   93.99   94.7200   92.51   93.74    -0.139921
2016-05-31   99.60  100.4000   98.82   99.86     0.065287
2016-06-30   94.44   95.7700   94.30   95.60    -0.042660
2016-07-31  104.19  104.5500  103.68  104.21     0.090063
2016-08-31  105.66  106.5699  105.64  106.10     0.018136
2016-09-30  112.46  113.3700  111.80  113.05     0.065504
2016-10-31  113.65  114.2300  113.20  113.54     0.004334
2016-11-30  111.56  112.2000  110.27  110.52    -0.026599
2016-12-31  116.65  117.2000  115.43  115.82     0.047955

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [34]:
# Se puede usar el metodo isnull para determinar como afectan los valores anormales en la serie

missing = aapl_bar.isnull()
print (missing)
print ('---------------------------------------------')
print (missing.describe())

             Open   High    Low  Close  rate_return
Date
2016-01-31  False  False  False  False         True
2016-02-29  False  False  False  False        False
2016-03-31  False  False  False  False        False
2016-04-30  False  False  False  False        False
2016-05-31  False  False  False  False        False
2016-06-30  False  False  False  False        False
2016-07-31  False  False  False  False        False
2016-08-31  False  False  False  False        False
2016-09-30  False  False  False  False        False
2016-10-31  False  False  False  False        False
2016-11-30  False  False  False  False        False
2016-12-31  False  False  False  False        False
---------------------------------------------
         Open   High    Low  Close rate_return
count      12     12     12     12          12
unique      1      1      1      1           2
top     False  False  False  False       False
freq       12     12     12     12          11

In [35]:
# Tambien se puede saber cuales filas tienen valores nulos

print(missing[missing.rate_return == True])

             Open   High    Low  Close  rate_return
Date
2016-01-31  False  False  False  False         True

In [36]:
# Los valores faltantes se puden descartar o llenar, igual que en las series

drop = aapl_bar.dropna()
print (drop)
print ('\n--------------------------------------------------\n')
fill = aapl_bar.fillna(0)
print (fill)

              Open      High     Low   Close  rate_return
Date
2016-02-29   96.86   98.2300   96.65   96.69    -0.006678
2016-03-31  109.72  109.9000  108.88  108.99     0.127211
2016-04-30   93.99   94.7200   92.51   93.74    -0.139921
2016-05-31   99.60  100.4000   98.82   99.86     0.065287
2016-06-30   94.44   95.7700   94.30   95.60    -0.042660
2016-07-31  104.19  104.5500  103.68  104.21     0.090063
2016-08-31  105.66  106.5699  105.64  106.10     0.018136
2016-09-30  112.46  113.3700  111.80  113.05     0.065504
2016-10-31  113.65  114.2300  113.20  113.54     0.004334
2016-11-30  111.56  112.2000  110.27  110.52    -0.026599
2016-12-31  116.65  117.2000  115.43  115.82     0.047955

--------------------------------------------------

              Open      High     Low   Close  rate_return
Date
2016-01-31   94.79   97.3400   94.35   97.34     0.000000
2016-02-29   96.86   98.2300   96.65   96.69    -0.006678
2016-03-31  109.72  109.9000  108.88  108.99     0.127211
2016-04-30   93.99   94.7200   92.51   93.74    -0.139921
2016-05-31   99.60  100.4000   98.82   99.86     0.065287
2016-06-30   94.44   95.7700   94.30   95.60    -0.042660
2016-07-31  104.19  104.5500  103.68  104.21     0.090063
2016-08-31  105.66  106.5699  105.64  106.10     0.018136
2016-09-30  112.46  113.3700  111.80  113.05     0.065504
2016-10-31  113.65  114.2300  113.20  113.54     0.004334
2016-11-30  111.56  112.2000  110.27  110.52    -0.026599
2016-12-31  116.65  117.2000  115.43  115.82     0.047955

In [37]:
# Es posible concatenar los dataframes con concat

s1 = pd.Series([143.5, 144.09, 142.73, 144.18, 143.77], name = 'AAPL')
s2 = pd.Series([898.7, 911.71, 906.69, 918.59, 926.99], name = 'GOOG')
data_frame = pd.concat([s1, s2], axis = 1)
print (data_frame)

     AAPL    GOOG
0  143.50  898.70
1  144.09  911.71
2  142.73  906.69
3  144.18  918.59
4  143.77  926.99

In [39]:
import numpy as np

# Axis = 1 permite que se concatenen los dataframes por columnas

log_price = np.log(aapl_bar.Close)
log_price.name = 'log_price'
print (log_price)
print ('\n--------------------------------------------\n')
concat = pd.concat([aapl_bar, log_price], axis = 1)
print (concat)

Date
2016-01-31    4.578210
2016-02-29    4.571510
2016-03-31    4.691256
2016-04-30    4.540525
2016-05-31    4.603769
2016-06-30    4.560173
2016-07-31    4.646408
2016-08-31    4.664382
2016-09-30    4.727830
2016-10-31    4.732155
2016-11-30    4.705197
2016-12-31    4.752037
Freq: M, Name: log_price, dtype: float64

--------------------------------------------

              Open      High     Low   Close  rate_return  log_price
Date
2016-01-31   94.79   97.3400   94.35   97.34          NaN   4.578210
2016-02-29   96.86   98.2300   96.65   96.69    -0.006678   4.571510
2016-03-31  109.72  109.9000  108.88  108.99     0.127211   4.691256
2016-04-30   93.99   94.7200   92.51   93.74    -0.139921   4.540525
2016-05-31   99.60  100.4000   98.82   99.86     0.065287   4.603769
2016-06-30   94.44   95.7700   94.30   95.60    -0.042660   4.560173
2016-07-31  104.19  104.5500  103.68  104.21     0.090063   4.646408
2016-08-31  105.66  106.5699  105.64  106.10     0.018136   4.664382
2016-09-30  112.46  113.3700  111.80  113.05     0.065504   4.727830
2016-10-31  113.65  114.2300  113.20  113.54     0.004334   4.732155
2016-11-30  111.56  112.2000  110.27  110.52    -0.026599   4.705197
2016-12-31  116.65  117.2000  115.43  115.82     0.047955   4.752037

In [40]:
# Tambien se pueden unir por filas

df_volume = aapl_table.loc['2016-10':'2017-04', ['Volume', 'Split Ratio']].resample('M').agg(lambda x: x[-1])
print (df_volume)
print ('\n-------------------------------------------\n')
df_2017 = aapl_table.loc['2016-10':'2017-04', ['Open', 'High', 'Low', 'Close']].resample('M').agg(lambda x: x[-1])
print (df_2017)

                Volume  Split Ratio
Date
2016-10-31  26419398.0          1.0
2016-11-30  36162258.0          1.0
2016-12-31  30586265.0          1.0
2017-01-31  49200993.0          1.0
2017-02-28  23482860.0          1.0
2017-03-31  19661651.0          1.0
2017-04-30  20247187.0          1.0

-------------------------------------------

              Open     High     Low   Close
Date
2016-10-31  113.65  114.230  113.20  113.54
2016-11-30  111.56  112.200  110.27  110.52
2016-12-31  116.65  117.200  115.43  115.82
2017-01-31  121.15  121.390  120.62  121.35
2017-02-28  137.08  137.435  136.70  136.99
2017-03-31  143.72  144.270  143.01  143.66
2017-04-30  144.09  144.300  143.27  143.65

In [41]:
concat = pd.concat([aapl_bar, df_volume], axis = 1)
print(concat)

              Open      High     Low  ...  rate_return      Volume  Split Ratio
Date                                  ...
2016-01-31   94.79   97.3400   94.35  ...          NaN         NaN          NaN
2016-02-29   96.86   98.2300   96.65  ...    -0.006678         NaN          NaN
2016-03-31  109.72  109.9000  108.88  ...     0.127211         NaN          NaN
2016-04-30   93.99   94.7200   92.51  ...    -0.139921         NaN          NaN
2016-05-31   99.60  100.4000   98.82  ...     0.065287         NaN          NaN
2016-06-30   94.44   95.7700   94.30  ...    -0.042660         NaN          NaN
2016-07-31  104.19  104.5500  103.68  ...     0.090063         NaN          NaN
2016-08-31  105.66  106.5699  105.64  ...     0.018136         NaN          NaN
2016-09-30  112.46  113.3700  111.80  ...     0.065504         NaN          NaN
2016-10-31  113.65  114.2300  113.20  ...     0.004334  26419398.0          1.0
2016-11-30  111.56  112.2000  110.27  ...    -0.026599  36162258.0          1.0
2016-12-31  116.65  117.2000  115.43  ...     0.047955  30586265.0          1.0
2017-01-31     NaN       NaN     NaN  ...          NaN  49200993.0          1.0
2017-02-28     NaN       NaN     NaN  ...          NaN  23482860.0          1.0
2017-03-31     NaN       NaN     NaN  ...          NaN  19661651.0          1.0
2017-04-30     NaN       NaN     NaN  ...          NaN  20247187.0          1.0

[16 rows x 7 columns]

In [42]:
# Tambien se puede unir medienta la intersección  para esto se  utiliza el atributo inner

concat = pd.concat([aapl_bar, df_volume], axis = 1, join = 'inner')
print (concat)

              Open    High     Low  ...  rate_return      Volume  Split Ratio
Date                                ...
2016-10-31  113.65  114.23  113.20  ...     0.004334  26419398.0          1.0
2016-11-30  111.56  112.20  110.27  ...    -0.026599  36162258.0          1.0
2016-12-31  116.65  117.20  115.43  ...     0.047955  30586265.0          1.0

[3 rows x 7 columns]

In [43]:
append = aapl_bar.append(df_2017)
print (append)

              Open      High     Low   Close  rate_return
Date
2016-01-31   94.79   97.3400   94.35   97.34          NaN
2016-02-29   96.86   98.2300   96.65   96.69    -0.006678
2016-03-31  109.72  109.9000  108.88  108.99     0.127211
2016-04-30   93.99   94.7200   92.51   93.74    -0.139921
2016-05-31   99.60  100.4000   98.82   99.86     0.065287
2016-06-30   94.44   95.7700   94.30   95.60    -0.042660
2016-07-31  104.19  104.5500  103.68  104.21     0.090063
2016-08-31  105.66  106.5699  105.64  106.10     0.018136
2016-09-30  112.46  113.3700  111.80  113.05     0.065504
2016-10-31  113.65  114.2300  113.20  113.54     0.004334
2016-11-30  111.56  112.2000  110.27  110.52    -0.026599
2016-12-31  116.65  117.2000  115.43  115.82     0.047955
2016-10-31  113.65  114.2300  113.20  113.54          NaN
2016-11-30  111.56  112.2000  110.27  110.52          NaN
2016-12-31  116.65  117.2000  115.43  115.82          NaN
2017-01-31  121.15  121.3900  120.62  121.35          NaN
2017-02-28  137.08  137.4350  136.70  136.99          NaN
2017-03-31  143.72  144.2700  143.01  143.66          NaN
2017-04-30  144.09  144.3000  143.27  143.65          NaN

In [44]:
# Se pueden unir los dataframe con axis 0, y esto reemplaza append
concat = pd.concat([aapl_bar, df_2017], axis = 0)
print(concat)

              Open      High     Low   Close  rate_return
Date
2016-01-31   94.79   97.3400   94.35   97.34          NaN
2016-02-29   96.86   98.2300   96.65   96.69    -0.006678
2016-03-31  109.72  109.9000  108.88  108.99     0.127211
2016-04-30   93.99   94.7200   92.51   93.74    -0.139921
2016-05-31   99.60  100.4000   98.82   99.86     0.065287
2016-06-30   94.44   95.7700   94.30   95.60    -0.042660
2016-07-31  104.19  104.5500  103.68  104.21     0.090063
2016-08-31  105.66  106.5699  105.64  106.10     0.018136
2016-09-30  112.46  113.3700  111.80  113.05     0.065504
2016-10-31  113.65  114.2300  113.20  113.54     0.004334
2016-11-30  111.56  112.2000  110.27  110.52    -0.026599
2016-12-31  116.65  117.2000  115.43  115.82     0.047955
2016-10-31  113.65  114.2300  113.20  113.54          NaN
2016-11-30  111.56  112.2000  110.27  110.52          NaN
2016-12-31  116.65  117.2000  115.43  115.82          NaN
2017-01-31  121.15  121.3900  120.62  121.35          NaN
2017-02-28  137.08  137.4350  136.70  136.99          NaN
2017-03-31  143.72  144.2700  143.01  143.66          NaN
2017-04-30  144.09  144.3000  143.27  143.65          NaN

In [46]:
# Si las columnas de los dataframes a ser unidos se llaman igual, estas simplemente se unen

df_2017.columns = ['Change', 'High', 'Low', 'Close']
concat = pd.concat([aapl_bar, df_2017], axis = 0)
print (concat)

              Open      High     Low   Close  rate_return  Change
Date
2016-01-31   94.79   97.3400   94.35   97.34          NaN     NaN
2016-02-29   96.86   98.2300   96.65   96.69    -0.006678     NaN
2016-03-31  109.72  109.9000  108.88  108.99     0.127211     NaN
2016-04-30   93.99   94.7200   92.51   93.74    -0.139921     NaN
2016-05-31   99.60  100.4000   98.82   99.86     0.065287     NaN
2016-06-30   94.44   95.7700   94.30   95.60    -0.042660     NaN
2016-07-31  104.19  104.5500  103.68  104.21     0.090063     NaN
2016-08-31  105.66  106.5699  105.64  106.10     0.018136     NaN
2016-09-30  112.46  113.3700  111.80  113.05     0.065504     NaN
2016-10-31  113.65  114.2300  113.20  113.54     0.004334     NaN
2016-11-30  111.56  112.2000  110.27  110.52    -0.026599     NaN
2016-12-31  116.65  117.2000  115.43  115.82     0.047955     NaN
2016-10-31     NaN  114.2300  113.20  113.54          NaN  113.65
2016-11-30     NaN  112.2000  110.27  110.52          NaN  111.56
2016-12-31     NaN  117.2000  115.43  115.82          NaN  116.65
2017-01-31     NaN  121.3900  120.62  121.35          NaN  121.15
2017-02-28     NaN  137.4350  136.70  136.99          NaN  137.08
2017-03-31     NaN  144.2700  143.01  143.66          NaN  143.72
2017-04-30     NaN  144.3000  143.27  143.65          NaN  144.09

# Fin